// Generates the C# game-data layer from the real TypeScript defs in ../shared.
//
// shared/defs is the single source of truth for game data (757+ game types,
// 1072+ map types, protocol version, bag/inventory order, biome colors, ...).
// Hand-transcribing it into C# would drift immediately, so this script imports
// the live TS registry (Node type-stripping) and emits C# into
// Assets/Scripts/Generated/.
//
// Usage (from client-unity-mobile/):
//   node --experimental-transform-types tools/codegen-defs.mjs
//
// The generated files are deterministic; commit them but only via this script.
// This is the Unity counterpart of the codegen used by the other native port
// described in ../client-mobile (same shared sources, different output language).
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const sharedDir = path.resolve(root, "..", "shared");
const outDir = path.join(root, "Assets", "Scripts", "Generated");

function argValue(name, fallback) {
    const i = process.argv.indexOf(name);
    return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}
const registryPath = argValue("--register", path.join(sharedDir, "defs", "register.ts"));
const configPath = argValue("--config", path.join(sharedDir, "gameConfig.ts"));

if (!fs.existsSync(registryPath)) {
    throw new Error(`defs registry not found: ${registryPath}`);
}

fs.mkdirSync(outDir, { recursive: true });

// The registry exposes `typeToId` as a method, so insertion order is read by
// probing ids from 0 upwards (id 0 is the empty type). The probe stops at the
// first gap; `idToType` prints to stderr for an out-of-range id, which is fine.
function readTypeToId(register) {
    const map = {};
    for (let id = 0; id < 8192; id++) {
        const type = register.idToType(id);
        if (typeof type !== "string" || (type.length === 0 && id !== 0)) break;
        map[type] = id;
    }
    return map;
}

function pathToFileUrl(p) {
    return new URL(`file://${p.replace(/\\/g, "/")}`).href;
}

async function main() {
    const mod = await import(pathToFileUrl(registryPath));
    const gameTypes = readTypeToId(mod.GameObjectDefs);
    const mapTypes = readTypeToId(mod.MapObjectDefs);

    const lines = [];
    lines.push("// <auto-generated>");
    lines.push("// Generated by tools/codegen-defs.mjs from ../shared/defs. DO NOT EDIT.");
    lines.push("// </auto-generated>");
    lines.push("namespace Survev.Core.Generated");
    lines.push("{");
    lines.push("    public static class GeneratedDefs");
    lines.push("    {");
    lines.push("        // Protocol-visible game type -> id mapping (insertion order).");
    lines.push("        public static readonly System.Collections.Generic.Dictionary<string, int> GameTypeToId =");
    lines.push("            new System.Collections.Generic.Dictionary<string, int>");
    lines.push("        {");
    for (const [type, id] of Object.entries(gameTypes)) {
        lines.push(`            { "${type}", ${id} },`);
    }
    lines.push("        };");
    lines.push("");
    lines.push("        // Protocol-visible map type -> id mapping (insertion order).");
    lines.push("        public static readonly System.Collections.Generic.Dictionary<string, int> MapTypeToId =");
    lines.push("            new System.Collections.Generic.Dictionary<string, int>");
    lines.push("        {");
    for (const [type, id] of Object.entries(mapTypes)) {
        lines.push(`            { "${type}", ${id} },`);
    }
    lines.push("        };");
    lines.push("    }");
    lines.push("}");
    lines.push("");

    const outFile = path.join(outDir, "GeneratedDefs.cs");
    fs.writeFileSync(outFile, lines.join("\n"));
    console.log(
        `done: ${Object.keys(gameTypes).length} game types, ${Object.keys(mapTypes).length} map types -> ${
            path.relative(root, outFile)
        }`,
    );

    // TODO: also emit gameConfig constants, biome colors, map-object images,
    // colliders and structure layers once the corresponding extractors land.
    if (!fs.existsSync(configPath)) {
        console.warn(`note: gameConfig not found: ${configPath}`);
    }
}

main().catch((err) => {
    console.error(err.message);
    process.exit(1);
});
