// Port of the type<->id registries used by the wire format
// (shared/defs/register.ts, consumed by net.ts writeGameType/writeMapType).
//
// The id tables are GENERATED by tools/codegen-defs.mjs (Assets/Scripts/Generated
// /GeneratedDefs.cs) and must match the server byte-for-byte. This wrapper adds
// the reverse lookup so readGameType/readMapType are O(1).
using System.Collections.Generic;
using Survev.Core.Generated;

namespace Survev.Net
{
    /// <summary>Runtime type registry built from the generated id tables.</summary>
    public static class TypeRegistry
    {
        private static readonly Dictionary<string, int> GameToId = GeneratedDefs.GameTypeToId;
        private static readonly Dictionary<string, int> MapToId = GeneratedDefs.MapTypeToId;
        private static readonly Dictionary<int, string> GameFromId = BuildReverse(GameToId);
        private static readonly Dictionary<int, string> MapFromId = BuildReverse(MapToId);

        public static int GameTypeToId(string type)
        {
            return GameToId.TryGetValue(type, out int id) ? id : 0;
        }

        public static string GameIdToType(int id)
        {
            return GameFromId.TryGetValue(id, out string type) ? type : string.Empty;
        }

        public static int MapTypeToId(string type)
        {
            return MapToId.TryGetValue(type, out int id) ? id : 0;
        }

        public static string MapIdToType(int id)
        {
            return MapFromId.TryGetValue(id, out string type) ? type : string.Empty;
        }

        private static Dictionary<int, string> BuildReverse(Dictionary<string, int> source)
        {
            var reverse = new Dictionary<int, string>(source.Count);
            foreach (var kv in source)
            {
                reverse[kv.Value] = kv.Key;
            }
            return reverse;
        }
    }
}